alertmanager:
  enabled: false

grafana:
  enabled: false

kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

prometheus:
  enabled: true

  serviceAccount:
    create: true
    name: "prometheus-sa"

  collector:
    disable-defaults: true

  ingress:
    enabled: false

  prometheusSpec:
    scrapeInterval: 10s
    evaluationInterval: 30s
    retention: 4d
    replicas: 2
    shards: 1

    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

cleanPrometheusOperatorObjectNames: true