loki:
  structuredConfig:
    compactor:
      shared_store: filesystem
      working_directory: /var/loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    limits_config:
      retention_period: 336h

compactor:
  enabled: true
  resources:
    requests:
      memory: "125Mi"
      cpu: "20m"
      
serviceAccount:
  enabled: true
  name: "loki-sa"