deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  limits_config:
    retention_period: 336h

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    storageClass: standard-rwo
    size: 5Gi

# Schakel gedistribueerde componenten uit (niet nodig in SingleBinary)
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

minio:
  enabled: false
