apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
  labels:
    app: public-cloud-concepts
    slot: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-cloud-concepts
      slot: blue
  template:
    metadata:
      labels:
        app: public-cloud-concepts
        slot: blue
    spec:
      containers:
        - name: app
          image: europe-west4-docker.pkg.dev/project-5b8c5498-4fe2-42b9-bc3/public-cloud-concepts/app:blue
          ports:
            - containerPort: 80
