apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
  labels:
    app: public-cloud-concepts
    slot: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-cloud-concepts
      slot: blue
  template:
    metadata:
      labels:
        app: public-cloud-concepts
        slot: blue
    spec:
      containers:
        - name: app
          image: ${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
