apiVersion: v1
kind: Service
metadata:
  name: public-cloud-concepts
spec:
  type: LoadBalancer
  selector:
    app: public-cloud-concepts
    slot: blue  # ← Verander naar "green" om te switchen naar de green versie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
